language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
script:
  - ./autogen.sh && ./configure && sudo make install
  - cd examples && make autobahn-echo && ./autobahn-echo 9001 &
  - sudo pip install autobahntestsuite
  - wstest -m fuzzingclient
