language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade Markdown
  - sudo pip install --upgrade --ignore-installed six
  - sudo pip install --upgrade zope.interface
  - sudo pip install autobahntestsuite --ignore-installed pyOpenSSL

script:
  - ./autogen.sh && ./configure && sudo make install && export LD_LIBRARY_PATH=/usr/local/lib
  - cd examples && make autobahn-echo && ./autobahn-echo 9001 &
  - wstest -m fuzzingclient
