language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
script:
  - ./autogen.sh && ./configure && sudo make install
  - cd examples && make autobahn-echo
  - sudo pip install autobahntestsuite
