language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo pip install autobahntestsuite

script:
  - ./autogen.sh && ./configure && sudo make install && export LD_LIBRARY_PATH=/usr/local/lib
  - cd examples && make autobahn-echo && ./autobahn-echo 9001 &
  - wstest --help
